"""Advisory Impact Checker — two-phase LLM+SSH agent with plan caching.

Phase 1 (Plan)  : Fetch full advisory page from Cisco → LLM reads it →
                  decides commands OR gives direct verdict.
                  Cached per advisory_id so subsequent devices skip this step.
Phase 2 (Assess): Run commands via SSH → LLM compares output vs advisory → verdict.
"""
from __future__ import annotations

import json
import logging
import os
import re
import sys
import threading
from html.parser import HTMLParser
from typing import Any, Callable

import requests

logger = logging.getLogger(__name__)

_THINK_RE = re.compile(r"<think>.*?</think>", re.DOTALL)
_JSON_BLOCK_RE = re.compile(r"\{.*\}", re.DOTALL)
_MAX_COMMANDS = int(os.getenv("ADVISORY_CHECK_MAX_COMMANDS", "5"))

# ── Full advisory page cache (text rarely changes, safe to cache) ──────────
_page_cache: dict[str, str] = {}
_page_cache_lock = threading.Lock()


class _TextExtractor(HTMLParser):
    """Extract readable text from Cisco advisory HTML page."""

    def __init__(self) -> None:
        super().__init__()
        self._parts: list[str] = []
        self._skip = False

    def handle_starttag(self, tag: str, attrs: list) -> None:
        if tag in ("script", "style", "nav", "footer", "header"):
            self._skip = True
        if tag in ("p", "li", "br", "h1", "h2", "h3", "h4", "tr", "div"):
            self._parts.append("\n")

    def handle_endtag(self, tag: str) -> None:
        if tag in ("script", "style", "nav", "footer", "header"):
            self._skip = False

    def handle_data(self, data: str) -> None:
        if not self._skip:
            self._parts.append(data)

    def get_text(self) -> str:
        text = "".join(self._parts)
        text = re.sub(r"[ \t]+", " ", text)
        text = re.sub(r"\n{3,}", "\n\n", text)
        return text.strip()


def _fetch_advisory_page(url: str) -> str:
    """Fetch full advisory page text from Cisco, with caching."""
    if not url:
        return ""

    with _page_cache_lock:
        if url in _page_cache:
            return _page_cache[url]

    try:
        resp = requests.get(url, timeout=15, headers={
            "User-Agent": "AIOps-Advisory-Checker/1.0",
            "Accept": "text/html",
        })
        if resp.status_code != 200:
            logger.warning("Advisory page fetch failed: %s → %d", url, resp.status_code)
            return ""

        parser = _TextExtractor()
        parser.feed(resp.text)
        text = parser.get_text()

        # Send full page to LLM — no trimming, no truncation

        with _page_cache_lock:
            _page_cache[url] = text

        return text
    except Exception as exc:
        logger.warning("Advisory page fetch error for %s: %s", url, exc)
        return ""


def _strip_think(text: str) -> str:
    return _THINK_RE.sub("", text).strip()


def _safe_json(text: str, fallback: dict) -> dict:
    clean = _strip_think(text)
    match = _JSON_BLOCK_RE.search(clean)
    if not match:
        return fallback
    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return fallback


def _llm_enabled() -> bool:
    if os.getenv("AIOPS_DISABLE_LLM", "").strip() == "1":
        return False
    if "pytest" in sys.modules or os.getenv("PYTEST_CURRENT_TEST"):
        return False
    return True


# ── Command normalization — fix common LLM syntax mistakes ────────────────
_CMD_REPLACEMENTS = [
    ("running-configuration", "running-config"),
    ("startup-configuration", "startup-config"),
    ("show ip ospf neighbour", "show ip ospf neighbor"),
    ("show ip eigrp neighbour", "show ip eigrp neighbor"),
]


def _normalize_ios_command(cmd: str) -> str:
    """Fix common Cisco IOS command syntax errors generated by LLM."""
    normalized = cmd.strip()
    for wrong, correct in _CMD_REPLACEMENTS:
        normalized = normalized.replace(wrong, correct)
    return normalized


def check_advisory_impact(
    *,
    device: dict[str, Any],
    advisory: dict[str, Any],
    on_event: Callable[[dict[str, Any]], None] | None = None,
) -> dict[str, Any]:
    """Two-phase LLM+SSH check with plan caching."""
    commands_run: list[dict[str, str]] = []

    def _emit(event_type: str, data: dict[str, Any]) -> None:
        if on_event:
            on_event({"type": event_type, **data})

    fallback: dict[str, Any] = {
        "verdict": "uncertain",
        "confidence": 0.0,
        "explanation": "Check could not complete — LLM or SSH not available.",
        "commands_run": commands_run,
    }

    if not _llm_enabled():
        return fallback

    hostname    = device.get("hostname", "")
    ip_address  = device.get("ip_address", "")
    os_platform = device.get("os_platform", "cisco_ios")

    if not ip_address:
        fallback["explanation"] = f"Device {hostname} has no IP address configured."
        return fallback

    try:
        from langchain_core.messages import HumanMessage
        from src.llm_factory import create_chat_model
        from src.tools.cli_tool import create_run_cli_tool

        device_cache = {
            hostname: {
                "ip_address": ip_address,
                "os_platform": os_platform,
                "device_role": device.get("device_role", ""),
                "site": device.get("site", ""),
                "version": device.get("version", ""),
            }
        }
        run_cli = create_run_cli_tool(device_cache)

        advisory_id = advisory.get("advisory_id", "")
        title       = advisory.get("title", "")
        sir         = advisory.get("sir", "")
        cvss_score  = advisory.get("cvss_score", 0)
        cves        = ", ".join(advisory.get("cves", [])[:5]) or advisory_id
        summary     = advisory.get("summary") or ""
        workaround  = advisory.get("workaround") or ""

        # ── PHASE 1: LLM reads CVE → plans commands ────────────────────────────

        _emit("status", {"message": f"Reading advisory page: {title[:55]}..."})

        pub_url   = advisory.get("publication_url") or ""
        logger.info("Advisory check: pub_url=%s", pub_url)
        full_page = _fetch_advisory_page(pub_url) if pub_url else ""

        if full_page:
            advisory_text = f"=== FULL ADVISORY PAGE ===\n{full_page}"
            _emit("status", {"message": "Analyzing advisory..."})
        else:
            advisory_text = (
                f"=== ADVISORY DESCRIPTION ===\n{summary}\n\n"
                f"Workaround / Mitigation:\n{workaround}"
            )
            _emit("status", {"message": "Page fetch failed, using API summary"})

        plan_prompt = (
            "You are a Cisco network security engineer.\n\n"
            f"Advisory ID : {advisory_id}\n"
            f"Severity    : [{sir}]  CVSS: {cvss_score}\n"
            f"Title       : {title}\n"
            f"CVEs        : {cves}\n\n"
            f"{advisory_text}\n\n"
            "=== YOUR TASK ===\n"
            "Read the advisory above — pay special attention to:\n"
            "  - 'Vulnerable Products' section\n"
            "  - 'Determine the Device Configuration' section\n"
            "  - Any specific `show` commands mentioned for verification\n\n"
            "Then decide:\n\n"
            "CASE A — The CVE requires a specific feature/config to be enabled.\n"
            "  (The advisory will usually say 'if X is configured' or 'disabled by default')\n"
            "  Device is only affected if that feature is configured and running.\n"
            f"  → Pick up to {_MAX_COMMANDS} READ-ONLY `show` commands to verify.\n"
            "  → If the advisory tells you exactly which command to use, USE THAT COMMAND.\n"
            "  → Return: {\"case\":\"A\",\"feature\":\"...\",\"commands\":[\"cmd1\",\"cmd2\",...]}\n\n"
            "CASE B — The CVE is in a core/always-on component.\n"
            "  (No specific feature needs to be enabled — all devices with this version are affected)\n"
            "  → Return: {\"case\":\"B\",\"feature\":\"...\",\"explanation\":\"...\"}\n\n"
            "CASE A rules:\n"
            "- Do NOT use `show version` — it only shows version, not feature status.\n"
            "- If the advisory says 'use show run | include X to check', use THAT command.\n"
            "- Use: show running-config | section <feature>\n"
            "- Use: show running-config | include <keyword>\n"
        )

        llm_plan  = create_chat_model(reasoning=True)
        reply     = llm_plan.invoke([HumanMessage(content=plan_prompt)])
        plan_text = _strip_think(str(getattr(reply, "content", "") or ""))
        plan      = _safe_json(plan_text, {})

        logger.info("Advisory plan: %s → case=%s feature=%s cmds=%s raw=%s",
                    advisory_id, plan.get("case"), plan.get("feature"),
                    plan.get("commands"), plan_text[:300])

        feature  = plan.get("feature", title)
        commands = plan.get("commands") or []

        _emit("plan", {"feature": feature, "commands": commands})

        if not commands and plan.get("case") != "B":
            logger.warning("Advisory plan returned no commands: %s raw=%s", advisory_id, plan_text[:200])

        # ── CASE B: Core vulnerability — verdict from version match ────────────

        if plan.get("case") == "B" or (not commands and plan.get("explanation")):
            explanation = str(plan.get("explanation") or f"Core vulnerability — all devices running this version are affected.")
            _emit("verdict", {"verdict": "affected", "confidence": 0.90, "explanation": explanation})
            return {
                "verdict": "affected",
                "confidence": 0.90,
                "explanation": explanation,
                "commands_run": [],
            }

        # ── CASE A: Run commands via SSH ───────────────────────────────────────

        if not commands:
            commands = ["show version"]

        commands = [_normalize_ios_command(c) for c in commands]

        for cmd in commands[:_MAX_COMMANDS]:
            _emit("step", {"command": cmd, "status": "running"})
            try:
                result     = run_cli.invoke({"host": hostname, "command": cmd})
                result_str = str(result)
            except Exception as ssh_exc:
                result_str = f"[SSH ERROR] {ssh_exc}"

            commands_run.append({"command": cmd, "output": result_str[:2000]})
            _emit("step", {"command": cmd, "output": result_str[:1200], "status": "done"})

        # ── Assess: single LLM call — output vs advisory → verdict ─────────────

        _emit("status", {"message": "Analyzing..."})

        evidence = "\n\n".join(
            f"$ {cr['command']}\n{cr['output'][:1000]}" for cr in commands_run
        )

        assess_prompt = (
            "/no_think\n"
            f"Advisory: [{sir}] {title}\n"
            f"CVEs: {cves}\n"
            f"Feature: {feature}\n\n"
            f"Advisory description:\n{summary}\n\n"
            f"CLI output from device {hostname}:\n{evidence}\n\n"
            "Is this feature configured and active on this device?\n\n"
            "CRITICAL RULES — read carefully:\n"
            "- 'show running-config | include X' with EMPTY output (no lines returned) "
            "means the config does NOT exist → not_affected\n"
            "- 'show running-config | section X' with EMPTY output means the feature "
            "is NOT configured → not_affected\n"
            "- DO NOT imagine or infer config lines that are not shown in the output above\n"
            "- Only say 'affected' if you can see ACTUAL config lines in the output\n"
            "- Config lines present (e.g. snmp-server, ip http server, webvpn) → affected\n"
            "- Service status shows Enabled/Active → affected\n"
            "- '% Invalid input' → command not supported → not_affected\n"
            "- Feature exists but explicitly disabled → not_affected\n"
            "- Use uncertain ONLY if ALL commands returned SSH errors\n\n"
            "Return ONLY JSON:\n"
            '{"verdict":"affected|not_affected","confidence":0.85-1.0,"explanation":"<cite the EXACT output>"}'
        )

        llm_assess   = create_chat_model(reasoning=False)
        assess_reply = llm_assess.invoke([HumanMessage(content=assess_prompt)])
        final_text   = _strip_think(str(getattr(assess_reply, "content", "") or ""))

        data      = _safe_json(final_text, {})
        verdict   = data.get("verdict", "")
        if verdict not in ("affected", "not_affected", "uncertain"):
            has_cli = any(not cr["output"].startswith("[SSH ERROR]") for cr in commands_run)
            verdict = "not_affected" if has_cli else "uncertain"
        confidence  = min(1.0, max(0.0, float(data.get("confidence") or 0.85)))
        explanation = str(data.get("explanation") or final_text[:500] or "No explanation provided.")

        _emit("verdict", {"verdict": verdict, "confidence": confidence, "explanation": explanation})

        return {
            "verdict": verdict,
            "confidence": confidence,
            "explanation": explanation,
            "commands_run": commands_run,
        }

    except Exception as exc:
        logger.exception(
            "Advisory check failed for device=%s advisory=%s: %s",
            hostname, advisory.get("advisory_id"), exc,
        )
        _emit("error", {"message": str(exc)})
        return {
            "verdict": "uncertain",
            "confidence": 0.0,
            "explanation": f"Check failed: {exc}",
            "commands_run": commands_run,
        }
